### ISSUE TITLE
Gene: Remove Name

### ISSUE THREAD

**Issue by Paul-Davis** [epaule/nameserver2#14]
Might be good if the secondary ID being removed is actually connected to the gene??

1   import  WBPerson1971    Tue, 30 Nov -001 00:01  CGC     -   -
1   addName     wormpub     Tue, 12 Sep 2006 17:50  CGC     cha-1   -
2   changeName  pad     Thu, 03 Oct 2013 13:24  CGC     unc-67  -
3   changeName  pad     Thu, 03 Oct 2013 13:24  Public_name     unc-67  -
4   delName     pad     Thu, 03 Oct 2013 13:25  CGC     unc-57  -
5   delName     pad     Thu, 03 Oct 2013 13:25  CGC     unc-67

4) was never a valid secondary ID??

**Comment by epaule** [comment]
done
