### ISSUE TITLE
Email output expected from NS2

### ISSUE THREAD

**Issue by Paul-Davis** [epaule/nameserver2#18]
If the formatting could be preserved, that would be good as the following are used by scripts to process the request into geneace.
## Merge Gene:

GENE MERGE
USER : pad - WBPerson1983
LIVE:retained geneID for Y35H6.3 - WBGene00021342
DEAD: killed geneID VY35H6BL.1 - WBGene00012160
## New gene:

newgene.pl -seq CE7X_3.4 -who 1983 -load -id WBGene00235377 -species elegans -species elegans
## Kill:

WBGene00021240
Remark "[pad] Converted this Gene into a Transposon_CDS/Pseudogene as it appears to be part of a transposable element."
WBPerson1983//  pad
## Split Gene:

splitgene.pl -old WBGene00021178 -new Y9C9A.112 -who 4025 -id WBGene00235376 -load -species elegans
## Change Class:

changegene.pl -seq CE7X_3.2 -who 1983 -load -class

would be good if it could include the 2 letter code CP (Pseudogene to CDS) etc. etc.

---

I might have missed one, but hopefully not??

P

**Comment by epaule** [comment]
merge_gene done

**Comment by epaule** [comment]
new_gene done

**Comment by epaule** [comment]
kill_gene done

**Comment by epaule** [comment]
split_gene done
