### ISSUE TITLE
Gene NS : Find a gene

### ISSUE THREAD

**Issue by tuli** [epaule/nameserver2#19]
Can we have a "clear" option so we can run another query or do we need to press "find gene" again to run a new query? 

nb. This is a suggested improvement to existing functionality.

**Comment by epaule** [comment]
I surely can add a "clear" button that links back to the find gene page that you can press instead of the link on the right side.

M

**Comment by Paul-Davis** [comment]
oh you are good michael, adding a new 1 click button to save the 1 click necessary to do another search ;) lol

**Comment by Paul-Davis** [comment]
while we are looking at this function/widget

What the....is this supposed to do?
![cancel](https://cloud.githubusercontent.com/assets/717707/3874960/ddd368e0-2149-11e4-9eb4-08892bfc9c0d.png)

It appears on all options, but doesn't really do much.

**Comment by epaule** [comment]
I restarted the dev-server, but my guess of how to remove it was wrong ... now contacting the source.

**Comment by epaule** [comment]
done
