### ISSUE TITLE
Gene NS : Find a gene (autocomplete)

### ISSUE THREAD

**Issue by tuli** [epaule/nameserver2#22]
Auto-complete is a bit funky.

I enter WBGene and it comes up with some suggestions based on what GeneIDs I've been using in this session, but underneath has some suggestions from the NS (or something). 

When I pick one of the ones I've been using in the session it actually uses the NS suggested ID which I think is underneath. 

Demo might be useful I think...

**Comment by epaule** [comment]
that is a rendering artifact, in as much as your browser shows ids from its browsing history which is on top of the javascript dropdown from the site ... I will forward that to James, who did the autocomplete stuff.

thanks,

M

**Comment by kyook** [comment]
Explain again?  The autocomplete is browser specific and only completes on what you've searched for before? It would be a lot nicer to have it autocomplete on what is in the actual database.

**Comment by Paul-Davis** [comment]
It looks like this issue is resolved??

https://app.box.com/shared/mke59ce6ey9rw4ckk6be

I no longer see a browser autocomplete, but the one coming directly from the NS

**Comment by epaule** [comment]
yup, James fixed that.

M
