### ISSUE TITLE
Error when adding new gene 

### ISSUE THREAD

**Issue by tuli** [epaule/nameserver2#24]
Adding Cbn-wdr-5.1 to brenneri (WBGene00163257) and I get 

Internal Server Error (500)
Your request for "/sanger/Worm_NameServer_Gene/add_name" failed. The reason is:

Unfortunately while trying to send you the contents that you requested, the server has hit a problem and cannot return what you have asked for.

**Comment by tuli** [comment]
Worked OK for similar action on briggsae

**Comment by tuli** [comment]
Worked OK for brenneri now. 

If you're happy this was just a blip, you may close the ticket.

**Comment by epaule** [comment]
hmm ... I tried it on my sandbox to get a proper error message ... but
sadly it works :-(

**Comment by epaule** [comment]
I will leave that one open for a bit ... in case we hit it again

**Comment by Paul-Davis** [comment]
Another error in this "New Gene" function

![clone list](https://f.cloud.github.com/assets/717707/1704755/e50f9a3c-60d0-11e3-99f8-a7996e56a3e6.png)

**Comment by epaule** [comment]
thanks, it is one of these "James only" permission things. I just sent an email in his direction to copy that file.

**Comment by epaule** [comment]
removed the clonelist bits from the code

**Comment by Paul-Davis** [comment]
so it should be working?

**Comment by epaule** [comment]
yup

**Comment by Paul-Davis** [comment]
cool will try it next time I find a new gene ;)
