### ISSUE TITLE
scripts

### ISSUE THREAD

**Issue by tuli** [epaule/nameserver2#25]
The following scripts use the gene NS in some way. 

batch_addname.pl
batch_delname.pl
batch_kill.pl
batch_merge.pl
id_resurrect.pl 
changegene.pl

**Comment by epaule** [comment]
... yeeeessss ?

**Comment by tuli** [comment]
So, they'll need to be updated to point to the new NS. Yes?

**Comment by epaule** [comment]
ok, I will bite:

the new "Nameserver" is just the web-fluff,  the regular API will work as before on the database. But we made some additions to the Nameserver for the new website (plus there are some philosophical changes that would be nice to do), that will be added to the one in CVS ... then we have it back to one API again.

**Comment by epaule** [comment]
no.
they will continue using the nameserver like they always have.
We will change/update the nameserver library one day, but it should work as
before as the changes will be at a place in the code that your scripts wont
touch.

**Comment by tuli** [comment]
OK. That's all OK then. Huzzah.
