### ISSUE TITLE
-species flag set and change_class option

### ISSUE THREAD

**Issue by Paul-Davis** [epaule/nameserver2#30]
Can we make sure that species is output for every action that generates a email

class change doesn't, could the code also make an attempt at adding the correct code

CP = Coding -> Pseudogene
PC = Pseudogene -> Coding

It is a fair guess that it is one of these combinations going to be used.

P

**Comment by epaule** [comment]
I can add a -species in the line for the script, but as we don't store the gene_class (yet), I can't add the change.

**Comment by Paul-Davis** [comment]
True, but the script is aware of what you are changing to as it adds it to the subject of the email, you could just use:

to Pseudogene add CP to command line
to CDS add PC to command line

Simples ;)

**Comment by epaule** [comment]
done
