### ISSUE TITLE
cannot perform the same task consecutively, e.g. merges/change of class

### ISSUE THREAD

**Issue by EleanorWB** [epaule/nameserver2#33]
If you merge a gene, get the results page confirming the merge, you are not able to click on the 'merge genes' link on the task menu to merge another pair of genes. I have seen the same behaviour with 'change class'. You have to choose another task and then ask again for what you wanted in the first place.
I hope that makes sense :)
Ele

**Comment by epaule** [comment]
Yes, I have seen that too. I think it came with the last Pagesmith update.
I will see what I can do.

M

**Comment by epaule** [comment]
bleh: it works on the test site: http://mh6-www.sandbox.sanger.ac.uk/sanger/Worm_NameServer_Gene/query

but not on the live one :-(

**Comment by epaule** [comment]
Ok, the pagesmith default changed. I pushed an update for just the menu, which should make it onto the live site in a few minutes.

**Comment by EleanorWB** [comment]
I can confirm that the issue is now resolved  :)
thank you
